# Generated by Django 4.2.9 on 2024-01-29 03:00

from django.db import migrations, models
import django.db.models.deletion
import jdih.custom_fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BentukPeraturan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nama_lengkap_bentuk",
                    models.CharField(
                        help_text="contoh: Peraturan Presiden",
                        max_length=100,
                        verbose_name="nama bentuk peraturan",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        default="", editable=False, max_length=100, unique=True
                    ),
                ),
                (
                    "singkatan_nama_bentuk",
                    models.CharField(
                        blank=True,
                        help_text="contoh: PP",
                        max_length=20,
                        null=True,
                        verbose_name="singkatan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Kategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("judul", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(default="", editable=False, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subyek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "judul",
                    models.CharField(
                        help_text="judul subyek atau tag", max_length=50, unique=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("judul", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(default="", editable=False, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Peraturan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kode",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="kode peraturan"
                    ),
                ),
                ("judul", models.CharField(max_length=300)),
                ("nomor", models.IntegerField(blank=True, null=True)),
                ("tahun", models.IntegerField(default=2024)),
                (
                    "unit_eselon_1_pemrakarsa",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "tempat_penetapan",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tanggal_penetapan", models.DateField(blank=True, null=True)),
                ("tanggal_pengundangan", models.DateField(blank=True, null=True)),
                ("tanggal_berlaku_efektif", models.DateField(blank=True, null=True)),
                (
                    "lokasi",
                    models.CharField(
                        blank=True,
                        help_text="contoh: Biro Hukum",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "sumber",
                    models.CharField(
                        blank=True,
                        help_text="contoh: BN nomor sekian",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "bahasa",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("indonesia", "Bahasa Indonesia"),
                            ("inggris", "Bahasa Inggris"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "bidang_hukum",
                    models.CharField(
                        blank=True,
                        help_text="contoh: Hukum Keuangan Negara",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("berlaku", "Berlaku"),
                            ("tidak_berlaku", "Tidak Berlaku"),
                        ],
                        default="berlaku",
                        max_length=50,
                    ),
                ),
                ("teks", models.TextField(blank=True, editable=False, null=True)),
                (
                    "file_dokumen",
                    jdih.custom_fields.ContentTypeRestrictedFileField(
                        blank=True, null=True, upload_to="dokumen_hukum/"
                    ),
                ),
                (
                    "bentuk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peraturans",
                        to="jdih.bentukperaturan",
                        verbose_name="bentuk peraturan",
                    ),
                ),
                ("kategori", models.ManyToManyField(blank=True, to="jdih.kategori")),
                (
                    "melengkapis",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pelengkaps",
                        to="jdih.peraturan",
                        verbose_name="melengkapi",
                    ),
                ),
                (
                    "mencabut_sebagians",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pencabut_sebagians",
                        to="jdih.peraturan",
                        verbose_name="mencabut sebagian",
                    ),
                ),
                (
                    "mencabuts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pencabuts",
                        to="jdih.peraturan",
                        verbose_name="mencabut seluruhnya",
                    ),
                ),
                (
                    "mengubahs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pengubahs",
                        to="jdih.peraturan",
                        verbose_name="mengubah",
                    ),
                ),
                (
                    "subyek",
                    models.ManyToManyField(
                        blank=True, to="jdih.subyek", verbose_name="subyek atau tag"
                    ),
                ),
                ("tema", models.ManyToManyField(blank=True, to="jdih.tema")),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
