# Generated by Django 4.2.9 on 2024-01-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jdih", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bentukperaturan",
            options={"verbose_name_plural": "bentuk peraturan"},
        ),
        migrations.AlterModelOptions(
            name="kategori",
            options={"verbose_name_plural": "kategori"},
        ),
        migrations.AlterModelOptions(
            name="peraturan",
            options={"ordering": ("-created_at",), "verbose_name_plural": "peraturan"},
        ),
        migrations.AlterModelOptions(
            name="subyek",
            options={"verbose_name_plural": "subyek"},
        ),
        migrations.AlterModelOptions(
            name="tema",
            options={"verbose_name_plural": "tema"},
        ),
        migrations.AddField(
            model_name="peraturan",
            name="last_teks_ingestion",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
