# Generated by Django 4.2.9 on 2024-01-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jdih", "0002_alter_bentukperaturan_options_alter_kategori_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="peraturan",
            name="jumlah_lihat",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="peraturan",
            name="jumlah_unduh",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="peraturan",
            name="last_teks_ingestion",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
