# Generated by Django 4.2.9 on 2024-02-15 08:28

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jdih", "0003_peraturan_jumlah_lihat_peraturan_jumlah_unduh_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="peraturan",
            name="teks_vektor",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, editable=False, null=True
            ),
        ),
    ]
