# Generated by Django 4.2.9 on 2024-05-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jdih", "0004_peraturan_teks_vektor"),
    ]

    operations = [
        migrations.AddField(
            model_name="bentukperaturan",
            name="displayed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="peraturan",
            name="mencabuts",
            field=models.ManyToManyField(
                blank=True,
                related_name="pencabuts",
                to="jdih.peraturan",
                verbose_name="mencabut/mengubah/melengkapi",
            ),
        ),
    ]
