# Generated by Django 4.2.9 on 2024-05-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jdih", "0006_rename_displayed_bentukperaturan_tayang"),
    ]

    operations = [
        migrations.AddField(
            model_name="peraturan",
            name="alasan_tidak_berlaku",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dicabut", "Dicabut"),
                    ("dicabut_sebagian", "Dicabut sebagian"),
                    ("diubah", "Diubah"),
                    ("dilengkapi", "Dilengkapi"),
                    ("lainnya", "Lainnya"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
