# Generated by Django 4.2.9 on 2024-05-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jdih", "0007_peraturan_alasan_tidak_berlaku"),
    ]

    operations = [
        migrations.AddField(
            model_name="peraturan",
            name="kode_judul",
            field=models.CharField(
                blank=True, editable=False, max_length=500, null=True
            ),
        ),
    ]
