# Generated by Django 4.2.9 on 2024-05-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jdih", "0008_peraturan_kode_judul"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="peraturan",
            index=models.Index(
                fields=["kode_judul"], name="jdih_peratu_kode_ju_0a9890_idx"
            ),
        ),
    ]
