# Generated by Django 4.2.9 on 2024-05-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jdih", "0009_peraturan_jdih_peratu_kode_ju_0a9890_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="peraturan",
            name="teks_ingestion_error_message",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
