# Generated by Django 4.2.9 on 2024-07-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jdih", "0010_peraturan_teks_ingestion_error_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peraturan",
            name="judul",
            field=models.CharField(
                help_text="Misalnya: Jam Kerja Pegawai di Lingkungan Kementerian Kesehatan Selama Bulan Ramadhan",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="peraturan",
            name="kode",
            field=models.CharField(
                help_text="Misalnya: HK.01.07/MENKES/123/2024",
                max_length=150,
                unique=True,
                verbose_name="kode peraturan",
            ),
        ),
        migrations.AlterField(
            model_name="peraturan",
            name="mencabuts",
            field=models.ManyToManyField(
                blank=True,
                related_name="pencabuts",
                to="jdih.peraturan",
                verbose_name="mencabut",
            ),
        ),
        migrations.AlterField(
            model_name="peraturan",
            name="mengubahs",
            field=models.ManyToManyField(
                blank=True,
                related_name="pengubahs",
                to="jdih.peraturan",
                verbose_name="mengubah/melengkapi",
            ),
        ),
        migrations.AlterField(
            model_name="peraturan",
            name="unit_eselon_1_pemrakarsa",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="eselon 1 pemrakarsa",
            ),
        ),
    ]
